#!/usr/bin/env bash
# ABOUTME: Creates an isolated throwaway git workspace for E2E runs.
# Copies test PRDs and initializes a clean baseline commit.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

WORKSPACE_PATH="${1:-$(mktemp -d "${TMPDIR:-/tmp}/ralph-tui-e2e-XXXXXX")}" 

if [[ -d "$WORKSPACE_PATH" ]]; then
  rm -rf "$WORKSPACE_PATH"
fi

mkdir -p "$WORKSPACE_PATH"

cp "$REPO_ROOT/testing/test-prd.json" "$WORKSPACE_PATH/test-prd.json"
cp "$REPO_ROOT/testing/test-conflict-prd.json" "$WORKSPACE_PATH/test-conflict-prd.json"
mkdir -p "$WORKSPACE_PATH/.ralph-tui/iterations"
cat > "$WORKSPACE_PATH/.gitignore" << 'GITIGNORE_EOF'
.ralph-tui/
GITIGNORE_EOF

cat > "$WORKSPACE_PATH/README.md" << 'WS_EOF'
# Ralph TUI E2E Throwaway Workspace

Temporary workspace generated by testing/e2e/setup-throwaway-workspace.sh.
WS_EOF

(
  cd "$WORKSPACE_PATH"
  git init --initial-branch=main >/dev/null
  git config user.name "ralph-e2e"
  git config user.email "ralph-e2e@example.com"
  git add .
  git commit -m "chore: init throwaway e2e workspace" >/dev/null
)

printf '%s\n' "$WORKSPACE_PATH"
